// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARb5Rg4LfuFV34bvN-G2YaLGtXxrQ5nTU',
    appId: '1:464153657950:web:ecc98bf86b4c3cb1fd2acf',
    messagingSenderId: '464153657950',
    projectId: 'smart-home-ba5dc',
    authDomain: 'smart-home-ba5dc.firebaseapp.com',
    storageBucket: 'smart-home-ba5dc.appspot.com',
    measurementId: 'G-YLFTRHV94N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAm0F5bHjKdRDgMHsmDbRxcq8ZMaf5IM',
    appId: '1:464153657950:android:21aaf930855605e9fd2acf',
    messagingSenderId: '464153657950',
    projectId: 'smart-home-ba5dc',
    storageBucket: 'smart-home-ba5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbdarFOF54Mmv3e_v305CqrQ3LQ83lNs',
    appId: '1:464153657950:ios:bdf58b444f06b5c1fd2acf',
    messagingSenderId: '464153657950',
    projectId: 'smart-home-ba5dc',
    storageBucket: 'smart-home-ba5dc.appspot.com',
    iosClientId: '464153657950-66v6k9gml12v8gmpitupiddkkhe30u0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbdarFOF54Mmv3e_v305CqrQ3LQ83lNs',
    appId: '1:464153657950:ios:bdf58b444f06b5c1fd2acf',
    messagingSenderId: '464153657950',
    projectId: 'smart-home-ba5dc',
    storageBucket: 'smart-home-ba5dc.appspot.com',
    iosClientId: '464153657950-66v6k9gml12v8gmpitupiddkkhe30u0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHomeApp',
  );
}
